/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package orderingsystem;

/**
 *
 * @author USER
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    Order orderList;
    public MainMenu() {
        initComponents();
    }
    public MainMenu(int i){
        initComponents();
        orderList=new Order();
    }
    public MainMenu(Order a) {
        initComponents();
        orderList=a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Wed = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        Fries = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        HotDog = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Munchies = new javax.swing.JButton();
        StrwShake = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        ChocShake = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ChezBurg = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        AloBurg = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Pepsi = new javax.swing.JButton();
        Sprite = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Ice = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        CLCake = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        Cookies = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        Pie = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        BurgerButton = new javax.swing.JLabel();
        ChiBurg = new javax.swing.JButton();
        BeefBurg = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 102));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        Wed.setBackground(new java.awt.Color(51, 255, 51));
        Wed.setText("Wedges");
        Wed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WedActionPerformed(evt);
            }
        });

        jLabel14.setText("Tk.60");

        Fries.setBackground(new java.awt.Color(0, 255, 0));
        Fries.setText("French Fries");
        Fries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FriesActionPerformed(evt);
            }
        });

        jLabel13.setText("Tk.50");

        HotDog.setBackground(new java.awt.Color(255, 204, 0));
        HotDog.setText("Hot Dog");
        HotDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HotDogActionPerformed(evt);
            }
        });

        jLabel12.setText("Tk.100");

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Snacks");

        Munchies.setBackground(new java.awt.Color(102, 153, 255));
        Munchies.setText("Munchies Fruit Shake");
        Munchies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MunchiesActionPerformed(evt);
            }
        });

        StrwShake.setBackground(new java.awt.Color(102, 153, 255));
        StrwShake.setText("Strawberry Milkshake");
        StrwShake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StrwShakeActionPerformed(evt);
            }
        });

        jLabel22.setText("Tk.120");

        jLabel21.setText("Tk.120");

        ChocShake.setBackground(new java.awt.Color(102, 153, 255));
        ChocShake.setText("Hersheys Choco Shake");
        ChocShake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChocShakeActionPerformed(evt);
            }
        });

        jLabel20.setText("Tk.140");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Shakes");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Drinks");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Soft-Drinks");

        ChezBurg.setBackground(new java.awt.Color(0, 153, 0));
        ChezBurg.setForeground(new java.awt.Color(255, 255, 255));
        ChezBurg.setText("Cheese Burst");
        ChezBurg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChezBurgActionPerformed(evt);
            }
        });

        jLabel11.setText("Tk.150");

        AloBurg.setBackground(new java.awt.Color(0, 153, 0));
        AloBurg.setForeground(new java.awt.Color(255, 255, 255));
        AloBurg.setText("Aloo Tikki");
        AloBurg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AloBurgActionPerformed(evt);
            }
        });

        jLabel10.setText("Tk.80");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Vegan");

        Pepsi.setBackground(new java.awt.Color(0, 153, 255));
        Pepsi.setText("Pepsi");
        Pepsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PepsiActionPerformed(evt);
            }
        });

        Sprite.setBackground(new java.awt.Color(0, 153, 255));
        Sprite.setText("Sprite");
        Sprite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpriteActionPerformed(evt);
            }
        });

        jLabel19.setText("Tk.30");

        jLabel4.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Dessert");

        Ice.setBackground(new java.awt.Color(0, 204, 204));
        Ice.setText("Ice-Cream");
        Ice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IceActionPerformed(evt);
            }
        });

        jLabel15.setText("Tk.60");

        CLCake.setBackground(new java.awt.Color(0, 204, 204));
        CLCake.setText("Choco Lava Cake");
        CLCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLCakeActionPerformed(evt);
            }
        });

        jLabel16.setText("Tk.120");

        Cookies.setBackground(new java.awt.Color(0, 204, 204));
        Cookies.setText("Cookies");
        Cookies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CookiesActionPerformed(evt);
            }
        });

        jLabel18.setText("Tk.90");

        Pie.setBackground(new java.awt.Color(0, 204, 204));
        Pie.setText("Cream Pie");
        Pie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PieActionPerformed(evt);
            }
        });

        jLabel17.setText("Tk.60");

        BurgerButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BurgerButton.setForeground(new java.awt.Color(0, 0, 0));
        BurgerButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BurgerButton.setText("Burgers");

        ChiBurg.setBackground(new java.awt.Color(204, 0, 0));
        ChiBurg.setForeground(new java.awt.Color(255, 255, 255));
        ChiBurg.setText("Chicken Delight");
        ChiBurg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChiBurgActionPerformed(evt);
            }
        });

        BeefBurg.setBackground(new java.awt.Color(204, 0, 51));
        BeefBurg.setForeground(new java.awt.Color(255, 255, 255));
        BeefBurg.setText("Beef Delight");
        BeefBurg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeefBurgActionPerformed(evt);
            }
        });

        jLabel5.setText("Tk.220");

        jLabel6.setText("Tk.250");

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Non-Vegan");

        jPanel2.setBackground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton1.setBackground(new java.awt.Color(153, 0, 51));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Create Your Own Burger!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CLCake)
                    .addComponent(Ice, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cookies, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pie, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel16))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabel19)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(217, 217, 217)
                                .addComponent(BurgerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jLabel1)
                                .addGap(222, 222, 222)
                                .addComponent(jLabel2)))
                        .addGap(259, 259, 259)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(438, 438, 438)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Pepsi)
                            .addComponent(jLabel8)
                            .addComponent(Sprite))
                        .addGap(177, 177, 177)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BeefBurg, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addGap(106, 106, 106)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(ChocShake)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(ChezBurg)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel11)
                                                .addGap(155, 155, 155)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(1, 1, 1)
                                                                .addComponent(Wed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                            .addComponent(Fries))
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(12, 12, 12)
                                                                .addComponent(jLabel13))
                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel15))))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(HotDog, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel12)))
                                                .addGap(6, 6, 6))
                                            .addComponent(StrwShake, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Munchies, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel21)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ChiBurg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addGap(111, 111, 111)
                                .addComponent(AloBurg, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)))))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(BurgerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(40, 40, 40)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(HotDog)
                    .addComponent(AloBurg)
                    .addComponent(jLabel10)
                    .addComponent(ChiBurg)
                    .addComponent(jLabel5))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BeefBurg)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ChezBurg)
                            .addComponent(jLabel11)))
                    .addComponent(Fries)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel13)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(Wed))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel4)
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addGap(45, 45, 45)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(Ice)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(ChocShake)
                            .addComponent(Pepsi))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(CLCake)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel19)
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(StrwShake))))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel17)
                                .addComponent(Cookies))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel21)
                                .addComponent(Munchies)))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(Pie)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(Sprite)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChiBurgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChiBurgActionPerformed
        Burger b=new ChickenDelight();
        BurgerSelection bs=new BurgerSelection(b,orderList);
        bs.setVisible(true);
        dispose();
    }//GEN-LAST:event_ChiBurgActionPerformed

    private void BeefBurgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeefBurgActionPerformed
        Burger b=new BeefDelight();
        BurgerSelection bs=new BurgerSelection(b,orderList);
        bs.setVisible(true);
        dispose();
    }//GEN-LAST:event_BeefBurgActionPerformed

    private void AloBurgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AloBurgActionPerformed
        Burger b=new AlooTikki();
        BurgerSelection bs=new BurgerSelection(b,orderList);
        bs.setVisible(true);
        dispose();
    }//GEN-LAST:event_AloBurgActionPerformed

    private void ChezBurgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChezBurgActionPerformed
        Burger b=new CheeseBurst();
        BurgerSelection bs=new BurgerSelection(b,orderList);
        bs.setVisible(true);
        dispose();
    }//GEN-LAST:event_ChezBurgActionPerformed

    private void HotDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HotDogActionPerformed
        Snacks b=new HotDog();
        FinalOrder bs=new FinalOrder(b,orderList);
        bs.setVisible(true);
        dispose();
    }//GEN-LAST:event_HotDogActionPerformed

    private void FriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FriesActionPerformed
        Snacks b=new FrenchFries();
        FinalOrder bs=new FinalOrder(b,orderList);
        bs.setVisible(true);
        dispose();
    }//GEN-LAST:event_FriesActionPerformed

    private void WedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WedActionPerformed
        Snacks b=new Wedges();
        FinalOrder bs=new FinalOrder(b,orderList);
        bs.setVisible(true);
        dispose();
    }//GEN-LAST:event_WedActionPerformed

    private void CLCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLCakeActionPerformed
        Dessert b=new ChocoLavaCake();
        FinalOrder bs=new FinalOrder(b,orderList);
        bs.setVisible(true);
        dispose();
    }//GEN-LAST:event_CLCakeActionPerformed

    private void CookiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CookiesActionPerformed
        Dessert b=new Cookies();
        FinalOrder bs=new FinalOrder(b,orderList);
        bs.setVisible(true);
        dispose();
    }//GEN-LAST:event_CookiesActionPerformed

    private void PieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PieActionPerformed
        Dessert b=new CreamPie();
        FinalOrder bs=new FinalOrder(b,orderList);
        bs.setVisible(true);
        dispose();
    }//GEN-LAST:event_PieActionPerformed

    private void IceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IceActionPerformed
        IceCream b=new IceCream();
        IceCreamSelection bs=new IceCreamSelection(b,orderList);
        bs.setVisible(true);
        dispose();
    }//GEN-LAST:event_IceActionPerformed

    private void ChocShakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChocShakeActionPerformed
        Drinks b=new Hersheys();
        FinalOrder bs=new FinalOrder(b,orderList);
        bs.setVisible(true);
        dispose();
    }//GEN-LAST:event_ChocShakeActionPerformed

    private void StrwShakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StrwShakeActionPerformed
        Drinks b=new Strawberry();
        FinalOrder bs=new FinalOrder(b,orderList);
        bs.setVisible(true);
        dispose();
    }//GEN-LAST:event_StrwShakeActionPerformed

    private void MunchiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MunchiesActionPerformed
        Drinks b=new Munchies();
        FinalOrder bs=new FinalOrder(b,orderList);
        bs.setVisible(true);
        dispose();
    }//GEN-LAST:event_MunchiesActionPerformed

    private void PepsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PepsiActionPerformed
        Drinks b=new Pepsi();
        FinalOrder bs=new FinalOrder(b,orderList);
        bs.setVisible(true);
        dispose();
    }//GEN-LAST:event_PepsiActionPerformed

    private void SpriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpriteActionPerformed
        Drinks b=new Sprite();
        FinalOrder bs=new FinalOrder(b,orderList);
        bs.setVisible(true);
        dispose();
    }//GEN-LAST:event_SpriteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Burger b=new Burger();
        b.setName("");
        b.setPrice(70);
        CustomBurger cb=new CustomBurger(b,orderList);
        cb.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AloBurg;
    private javax.swing.JButton BeefBurg;
    private javax.swing.JLabel BurgerButton;
    private javax.swing.JButton CLCake;
    private javax.swing.JButton ChezBurg;
    private javax.swing.JButton ChiBurg;
    private javax.swing.JButton ChocShake;
    private javax.swing.JButton Cookies;
    private javax.swing.JButton Fries;
    private javax.swing.JButton HotDog;
    private javax.swing.JButton Ice;
    private javax.swing.JButton Munchies;
    private javax.swing.JButton Pepsi;
    private javax.swing.JButton Pie;
    private javax.swing.JButton Sprite;
    private javax.swing.JButton StrwShake;
    private javax.swing.JButton Wed;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
